### ISSUE TITLE
[improvement] interest_over_time genreates "cannot reshape array of size 0 into shape (0,newaxis)"

### ISSUE THREAD

**Issue by simonsww** [sdil87/trendspy#3]
Hi，
Sometimes I may encounter rate limits, and sometimes there is indeed no data generated (when values are too low).
Currently, however, "interest_over_time" function always generates the error "cannot reshape array of size 0 into shape (0,newaxis)." 

Could you improve it so that I can distinguish whether I need to retry later or if the values themselves are genuinely empty?
Thank you!

**Comment by sdil87** [comment]
Hi! I've fixed this issue in the latest version (v0.1.2). Now instead of that confusing "cannot reshape array" error, you'll get an empty DataFrame when there's no data. 

You only need to retry your request if you get a 429 error. This happens either when you hit Google's rate limit or when their servers are under heavy load (not necessarily because of your requests). Otherwise, if you get an empty DataFrame, it just means there really isn't any data for your query - no need to retry in that case.

Let me know if you run into any other issues!

**Comment by simonsww** [comment]
Awesome,thank you very much!
